[versions]
atomic = "0.29.0"
build-config = "5.6.8"
coroutines = "1.10.2"
dokka = "2.0.0"
gradle-versions = "0.53.0"
mcp4k = "0.2.1" # Will be substituted
koja = "0.4.7"
kotlin = "2.3.0"
kotlinx-io-core = "0.7.0"
kotlinx-serialization = "1.9.0"
ksp-api = "2.3.0"
maven-publish = "0.34.0"
okio = "3.16.0"
spotless = "7.2.1"

[plugins]
build-config = { id = "com.github.gmazzo.buildconfig", version.ref = "build-config" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gradle-versions = { id = "com.github.ben-manes.versions", version.ref = "gradle-versions" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
ondrsh-mcp4k = { id = "sh.ondr.mcp4k", version.ref = "mcp4k" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
koja-runtime = { module = "sh.ondr.koja:koja-runtime", version.ref = "koja" }
koja-gradle = { module = "sh.ondr.koja:koja-gradle", version.ref = "koja" }
kotlin-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-compiler-embeddable", version.ref = "kotlin" }
kotlin-gradle-api = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin-api", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomic" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io-core"}
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp-api" }
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp-api" }
square-okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
square-okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
